### ISSUE TITLE
Tracking issue for 0.3.0 release

### ISSUE THREAD

**Issue by fitzgen** [rust-fuzz/arbitrary#19]
So we have some nice improvements to this crate, and I think everything has technically been compatible with a 0.2.X release but I think it is a good time to revisit some of the public API and trait designs and make a 0.3.0 release. I figured it would be good to open an issue to talk about what we might want in it.

## TODO

* [x] Fill out public API doc comments, and add examples to each of them
* [x] Better `Arbitrary` for `String` implementation (#17)
* [x] Should `Arbitrary` have `Debug` as a super trait? (#7)
* [x] Should `Arbitrary` have `Clone` as a super trait? This would allow easier/better shrinking implementations (e.g. for various collections)
* [x] Refactor `Unstructured` to look more like [`FuzzedDataProvider`](https://github.com/rust-fuzz/libfuzzer-sys/blob/master/libfuzzer/utils/FuzzedDataProvider.h)? In particular, maybe we should get lengths from the end of the buffer like that does.
* [x] Add `Arbitrary::arbitrary_take_rest` methods to consume the rest of an `Unstructured`. (#18)
* [x] Add `Arbitrary::size_hint` and refactor `Unstructured::container_size` into `Unstructured::collection_len`, as discussed in #18.
* [x] Add a `fn arbitrary<A: Arbitrary>(&mut self) -> Result<A, Self::Error>` helper method to `Unstructured` to shorten invoking nested-arbitrary calls, so you can just do `let foo = u.arbitrary()?;` and let type inference figure things out for you?

As we surface more things to be done for 0.3.0 in the comments, I'll add them to this list, so that we have a single place for everything.

------------------------------

+cc @Manishearth: what do you think? Anything we should add to or remove from this list?

**Comment by Manishearth** [comment]
The second last point is https://github.com/rust-fuzz/rust_arbitrary/issues/18

This seems about right, otherwise.

**Comment by fitzgen** [comment]
I kind of think we should get rid of `RingBuffer` and only have a finite buffer (that potentially gives out zeros after its exhausted).

Because the values from a ring buffer can end up getting interpreted in multiple different ways, it is hard for the fuzzer to make a small tweak to the input without having that affect the generated structure in many different ways. To move as close to "small change in raw input leads to small change in generated structure" we should only use finite buffers.

Thoughts @Manishearth?

**Comment by Manishearth** [comment]
Yeah, I don't think the ring buffer is useful. We can even make it so that it exits early if exhausted.

**Comment by fitzgen** [comment]
> The second last point is #18

yep, I tried to capture that in the item about making `Unstructured` look more like `FuzzedDataProvider`; did I overlook something there?

Also, given my last comment about finite vs ring buffers, maybe we can remove `Unstructured` as a trait and just have a single concrete input type? Or maybe it is useful to have something that users can extend? If we can't think of a good use case, it is probably best to remove it tho, to lower the cognitive overhead of the interface.

**Comment by fitzgen** [comment]
> We can even make it so that it exits early if exhausted.

Is this better than to give default values (i.e. zero) once exhausted? I don't have a good intuition for it.

**Comment by Manishearth** [comment]
I'm not sure. We should see what FuzzedDataProvider does.

**Comment by Manishearth** [comment]
On one hand, errorign early lets the fuzzer look for better input. On the other hand, we waste what could have been a useful cycle.

**Comment by fitzgen** [comment]
I guess maybe the give-me-a-default-value vs exist-early could be two different `Unstructured` trait impls. So maybe this is an argument for keeping the trait.

On the other hand, we could perform a quick test of say an hour of fuzzing with each variant and look at which ends up covering more code and then adopt that approach.

**Comment by Manishearth** [comment]
yeah, that makes sense. Might be worth talking to fuzzing experts as well.

**Comment by Manishearth** [comment]
There's an opportunity here for a smart adaptive system that can figure stuff out from available space and the components that need available space, but it sounds like a lot of work to design this general case.

**Comment by fitzgen** [comment]
> Should `Arbitrary` have `Clone` as a super trait? This would allow easier/better shrinking implementations (e.g. for various collections)

I'm going to vote "no" on this one. The collections shrinking was a little annoying to write, but we got it working, and I think the benefit of not forcing a bunch of required impls on people outweighs any gains we would get from it at this point.

Checking off this item, unless you feel strongly otherwise.

**Comment by fitzgen** [comment]
Ok I think once we merge #23 and #24 we are ready for a 0.3.0 release!

**Comment by fitzgen** [comment]
@Manishearth I'm going to bump this crate to 1.0-rc and do a release -- I feel pretty confident that `arbitrary` is in a good place, and think it's a good starting point for rolling out all these new releases cargo-fuzz, libfuzzer, and here.

Let me know if you have any concerns.
